name: Jackett

services:
  jackett:
    image: linuxserver/jackett:${JACKETT_VERSION}
    container_name: jackett
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - jackett_data:/config:rw
    ports:
      - '27.0.0.1:9117:9117'
    networks:
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true

networks:
  backend:
    external: true
    driver: bridge
    
volumes:
  jackett_data:
