name: Jackett

services:
  jackett:
    image: linuxserver/jackett:${JACKETT_VERSION}
    container_name: jackett
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - jackett_data:/config:rw
    ports:
      - "127.0.0.1:9117:9117"
    networks:
      - nginx-proxy-manager_frontend
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$

networks:
  nginx-proxy-manager_frontend:
    driver: bridge
    external: true

volumes:
  jackett_data:
